---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rmapi-token
  namespace: remarkable
spec:
  encryptedData:
    rmapi-token: AgAjc+Wz+Ws42Azi45mvBbWt2jNtw5xhe+cCDcL+PskPBfGe3Rd5n0NY4oYWWYb2m2rW307gAjJVX5zk9BCzBGJxZ3f+icSTPDVJc3vQCC/m4REGjliX1ec6an5Z1fo1OhfvSIYUeRS5FfkhStMICOpxrkLLFq1swB2RywmSUUiNNl2wWvifr1apOfke44/o2n1VQaiR8g5jFWmcfcp22GaN+MaObYrftb3wODfbdFWASUGmhpxGkXlLJlHajQGCeixhyG0jdKRw6ojAq3FX5tm6PTgcgmMXwKgNhb4knHT0NZ0QlK4GrOT5Xvo7jrZi1XZpv1n8OcwwdX/ISc6xOC3Yb8OBCY8OuFv9/kQj/xEu7mCtl5tQA0Fj4t/s6xQji2bwO+HT9sVA6UbulQfLZlsyYdjbysnFNbbVyB54Ulh/qpNEuXkODtMfYsoPKYdfV9+rDvMQFnzfD7E40zqFyPZeQHdAikdnxRb4X2kEThXOafjJ2DgMU+DU6EVb9c9f7BAUGKfEMo7IHkA+8IrjyAxYW9AzEniz7Bes3wXN2kL+T+xhdBYAj2GadV8b5WR0Ws4kvjI/yZmEgkHwjV8A3TYj3mggp7aMok3Q4l9XrZd6MxSHaDumiBB6yZYzDiOI9vaIiStH+pLOvhtEfBcRUCNED4i8XNjlcnP8lVpflco/GmvoPUeR1rq//WKsMXQAqLO+Jj9m1/K38T5Due949IlsqInbqAYBWZNW5zS7C+siwqdh+2vwifuUnSCPRHFVA5VAZQ7H3F1m3+FbJYEF1KyTs7KzPxpSnJ84ZLPLTW5IujHUopjFGvVhORyGwWcAoYWemTYWxSeEUVmyMqHUrVdJTua7Ll/qaQ+mxoEKNU7I7rCeN8G01TiS2MkHrrYQzAeI1NaWKnYC2DD9VKW//Y+DV8uH/TOxSMbdmuV+dpVzRFirfi1vObCeD5fFLvEJYpvnr7D3UlBiHG7ol+/MHWJDk0y8w92UmovSbm4SEehnZLEN6LsT2uLpgvWaXkkbJzjgwrrMqLNut5BPX6jc2vxapWZC/rttlLW99IND+0N4qynR6sYtXPgxQMnn75ZimagVEm42n0vsHYQuyuKfbkLtLcKX6O9p6Y6VndDN6YogcaLLttNDluX5EJI92UNJNTeoNpUX2UXS31G3rMQVkEL8leUhLQ1mPmT0p2LVcLDzlyBo2NfBqam82oyRLU9/6VOt
  template:
    metadata:
      creationTimestamp: null
      name: rmapi-token
      namespace: remarkable
